using UnityEngine;
using UnityEngine.InputSystem;

public class Transformplayer : MonoBehaviour
{
    private string positionState = "Room";
    private Quaternion defaultRotation = new Quaternion();
    public Transform room;
    public Transform balcony;
    public GameObject player;
    public InputActionReference action;
    void Start()
    {
        action.action.Enable();
        action.action.performed += TogglePosition;
        room.SetParent(player.transform);
        balcony.SetParent(player.transform);
    }

    // Idea to place the switch statement (made by me) to another function provided by ChatGPT, when asked if my code is functional
    // Function name and parameter generated by ChatGPT
    private void TogglePosition(InputAction.CallbackContext ctx) {
        switch (positionState)
        {
            // When the player is in the room, send them to the balcony coordinates and update the positionState to account for the new location
            case "Room":
                player.transform.SetPositionAndRotation(balcony.localPosition, defaultRotation);
                positionState = "Balcony";
                break;
    
            // And vice versa for when the player is at the balcony
            case "Balcony":
                player.transform.SetPositionAndRotation(room.localPosition, defaultRotation);
                positionState = "Room";
                break;
            
            default:
                break;
        }
    }
}
